## eureka Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/eureka:latest
          ports:
            - containerPort: 8761
## eureka Service
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - name: provider
      port: 8761
      targetPort: 8761
      nodePort: 30061

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/gateway:latest
          ports:
            - containerPort: 8805
          env:
            - name: active
              value: "prod"
            - name: eureka_host
              value: "eureka.default.svc.cluster.local"
            - name: eureka_port
              value: "8761"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: provider
      port: 8805
      targetPort: 8805
      nodePort: 30005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/user-service:latest
          ports:
            - containerPort: 8803
          env:
            - name: active
              value: "prod"
            - name: eureka_host
              value: "eureka.default.svc.cluster.local"
            - name: eureka_port
              value: "8761"

# user-edge-service Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-edge-service
spec:
  selector:
    matchLabels:
      app: user-edge-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-edge-service
    spec:
      containers:
        - name: user-edge-service
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/user-edge-service:latest
          ports:
            - containerPort: 8804
          env:
            - name: active
              value: "prod"
            - name: eureka_host
              value: "eureka.default.svc.cluster.local"
            - name: eureka_port
              value: "8761"

---
apiVersion: v1
kind: Service
metadata:
  name: user-edge-service
  labels:
    app: user-edge-service
spec:
  type: NodePort
  selector:
    app: user-edge-service
  ports:
    - name: provider
      port: 8804
      targetPort: 8804