apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - name: provider
      port: 8761
      targetPort: 8761
      nodePort: 30061

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/gateway:latest
          ports:
            - containerPort: 8805

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/eureka:latest
          ports:
            - containerPort: 8761

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/user-service:latest
          ports:
            - containerPort: 8803

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-edge-service
spec:
  selector:
    matchLabels:
      app: user-edge-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-edge-service
    spec:
      containers:
        - name: user-edge-service
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/user-edge-service:latest
          ports:
            - containerPort: 8804