---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          imagePullPolicy: Always
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/gateway:latest
          ports:
            - containerPort: 8805
          env:
            - name: active
              value: "prod"
            - name: eureka_host
              value: "eureka.default.svc.cluster.local"
            - name: eureka_port
              value: "8761"
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: provider
      port: 8805
      targetPort: 8805
      nodePort: 30005