---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          imagePullPolicy: Always
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/eureka:latest
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 300m
## eureka Service
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - name: provider
      port: 8761
      targetPort: 8761
      nodePort: 30061