apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-edge-service
spec:
  selector:
    matchLabels:
      app: user-edge-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-edge-service
    spec:
      containers:
        - name: user-edge-service
          imagePullPolicy: Always
          image: registry.cn-hangzhou.aliyuncs.com/micro-service-study/user-edge-service:latest
          env:
            - name: eureka_host
              value: "eureka.default.svc.cluster.local"
            - name: eureka_port
              value: "8761"
            - name: spring.profiles.active
              value: "prod"